package com.denimgroup.threadfix.framework.impl.rails.model;

import java.util.Collection;

public interface RailsRoutingEntry {

    void addChildEntry(RailsRoutingEntry child);
    void removeChildEntry(RailsRoutingEntry child);
    Collection<RailsRoutingEntry> getChildren();
    void setParent(RailsRoutingEntry parent);
    RailsRoutingEntry getParent();

    void onToken(int type, int lineNumber, String stringValue);
    void onParameter(String name, String value, RouteParameterValueType parameterType);
    void onInitializerParameter(int index, String value);

    void onBegin(String identifier);
    void onEnd();

    String getPrimaryPath(); // The main path for this entry that sub-routes will generally be relative to
    Collection<PathHttpMethod> getSubPaths(); // Sub-paths generated by this entry (NOT children)
    String getControllerName();
    String getActionMethodName();

    void setControllerName(String controllerName);
    void setActionMethodName(String actionMethodName);

    Collection<RouteCommonParameter> getSupportedDecorators();
    Collection<RouteCommonParameter> getCommonParameters();
    void addDecorator(RouteCommonParameter decorator);

    Collection<RouteShorthand> getSupportedShorthands();
    Collection<RouteShorthand> getShorthands();
    void addShorthand(RouteShorthand shorthand);

    RailsRoutingEntry cloneEntry();
}
